###############
### GENERAL ###
###############

general {
    gaps_in = 4
    gaps_out = 12
    border_size = 0
    col.active_border = rgb(585b70)
    col.inactive_border = rgb(2a2b36)
    layout = dwindle
    }


##################
### DECORATION ###
##################


# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 0.92

    dim_inactive = true
    dim_strength = 0.06

    shadow {
        enabled = true
        range = 20
        render_power = 3
        color = rgba(00000060)
        offset = 0 10
    }

############
### BLUR ###
############

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = true
        ignore_opacity = false
    }
}

###############
### LAYOUTS ###
###############


dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master


############
### MISC ###
############

}
misc {
    disable_hyprland_logo = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    vrr = 1
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

