###############
### GENERAL ###
###############

general {
    gaps_in = 4
    gaps_out = 12
    border_size = 0
    col.active_border = rgb(585b70)
    col.inactive_border = rgb(2a2b36)
    layout = dwindle
    }


##################
### DECORATION ###
##################


# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 18
    rounding_power = 2.4

    active_opacity = 1.0
    inactive_opacity = 0.92

    dim_inactive = true
    dim_strength = 0.06

    shadow {
        enabled = true
        range = 50
        render_power = 10
        color = rgba(00000027)
        offset = 0 4
        ignore_window = true
    }

############
### BLUR ###
############

    blur {
        enabled = false
        size = 10
        brightness = 1
        noise = 0.05
        contrast = 0.89
        passes = 3
        new_optimizations = true
        xray = true

        vibrancy = 0.5
        vibrancy_darkness = 0.5

        popups = false
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }
}

###############
### LAYOUTS ###
###############


dwindle {
    pseudotile = true 
    preserve_split = true
}

master {
    new_status = master


############
### MISC ###
############

}
misc {
    disable_hyprland_logo = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    vrr = 1
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

