###############
### GENERAL ###
###############

general {
    gaps_in = 4
    gaps_out = 12
    border_size = 0
    col.active_border = rgb(585b70)
    col.inactive_border = rgb(2a2b36)
    layout = dwindle
    }


##################
### DECORATION ###
##################


# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 0.92

    dim_inactive = true
    dim_strength = 0.06

    shadow {
        enabled = true
        range = 2
        render_power = 1
        color = rgba(00000099)
        offset = 0 10
    }

############
### BLUR ###
############

    blur {
        enabled = false
        size = 3
        passes = 3
        new_optimizations = true
        xray = false

        vibrancy = 0
        vibrancy_darkness = 0.38
    }
}

###############
### LAYOUTS ###
###############


dwindle {
    pseudotile = true 
    preserve_split = true
}

master {
    new_status = master


############
### MISC ###
############

}
misc {
    disable_hyprland_logo = true
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    vrr = 1
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

